### ISSUE TITLE
Correct classification of contentpass

### ISSUE THREAD

**Issue by ctavan** [cliqz-oss/whotracks.me#56]
I'm CTO and Co-Founder of [contentpass](https://www.contentpass.de/)

I believe that the current record about our service at https://whotracks.me/trackers/contentpass.html misrepresents what contentpass is actually doing and I would love to see the record corrected.

[contentpass offers cross-publisher subscriptions as well as consent management](https://medium.com/contentpass/privacy-pass-users-and-publishers-can-benefit-from-stronger-data-protection-f0adf05fd420) for news publishers. Publishers can make use of our product by including a JavaScript library which is hosted on our domain contentpass.net

Part of our solution is a statistics endpoint that helps publishers measure the usage of our product. Our JavaScript library sends measurement-signals to the stats endpoint on sites where our solution is being used, the endpoint is located at: https://api.contentpass.net/stats

We believe our solution is specifically interesting for privacy-aware users since – among others – it allows users to support publishers by paying a monthly subscription fee in exchange for removal of banner ads and tracking on the participating publisher sites. We're currently in the rollout process of our service: While the cross-publisher subscriptions are not available to the public yet, we're already integrating with many publishers and we're planning public availability within the next months. This is why our domains already appear on the whotracks.me database.

We have designed our service based on the principles of privacy-by-design and privacy-by-default. Among others, we take the following measures to protect the privacy of users visiting publisher websites where our service is implemented:

* we do not store any IP addresses (not even truncated IP addresses).
* we do not collect any personally identifiable information (PII).
* we do not collect any sort of unique user identifiers (uid) that would allow reconstruction of a browsing session.
* we do not collect device information which would allow device fingerprinting (i.e. no screen resolution, no information about installed plugins, etc.).
* we do not perform any cross-domain and/or 3rd-party tracking.

By the way, many of our design decisions were influenced by the ["Data Collection without Privacy Side-Effects" Paper](http://josepmpujol.net/public/papers/big_green_tracker.pdf).

We're also adhering to the [EFF Do Not Track (DNT) Policy](https://www.eff.org/dnt-policy) as we've recently [announced on our blog](https://medium.com/contentpass/how-contentpass-handles-user-data-40985bb6051a).

We believe that transparency is important and we therefore value your efforts with the whotracks.me database. However we also think that information shown there should be correct and not misleading.

We would therefore like to ask for our information to be corrected:

1. The record currently claims that we employ fingerprinting. This is not correct, we do not perform any fingerprinting, have never done so in the past and will never do it in the future. In fact, we do not even do anything that would qualify as "tracking" in the terms defined in the [What is a tracker?](https://whotracks.me/blog/what_is_a_tracker.html) blog post.
2. We're currently categorized as "Advertising", however we're doing quite the opposite: We're offering subscriptions for ad-free and premium access to publisher websites, as well as consent management. We think that the category "Essential" would describe much better what we're doing.

If you need any additional information I'm happy to provide it here. I also hope that opening an issue was the correct way of addressing this (since #51 is still open).

**Comment by sammacbeth** [comment]
Thanks for reaching out to us. We're working on improving the quality of our database, and are happy to amend entries when we get some information incorrect.

Regarding your requests:

 1. You are correct. We audited the scripts you have on focus.de and chip.de and found that there is no fingerprinting taking place. In fact, we were getting a signal that some data from the first-party cookie is being transmitted to your endpoint. As you mention, this method is preferable from a privacy-by-design standpoint, because it guarantees that cross-site tracking will not happen. This method was being aggregated under fingerprinting, which was not correct. We have corrected this, and the change will be reflected in the next data update we do for the site (planned for early March).
 2. Now that we have a better idea of what service you are offering, we will be able to update the category to something more appropriate. You mention that you will be providing subscription services for publishers. Based on that I would be inclined to categorise this as 'Customer Interaction' for the time being. The 'Essential' category is usually reserved for services without which sites would fail to function properly. Based on the current status I don't think there is a case for that classification yet.

Let let us know if that sounds reasonable to you, and thank you again for providing information to improve the accuracy and quality of our transparency tool.

**Comment by ctavan** [comment]
Thanks for taking a deeper look, @sammacbeth.

ad 1.) Great!
ad 2.) I understand your reasoning and agree that "Customer Interaction" may also be an appropriate classification for the current status of our product. The most important point for us is not being categorized as "Advertising" since we do to the exact opposite by helping publishers to deliver an advertising-free experience!

Please feel free to go ahead and close this issue as soon as the categorization has been fixed in master. Thank you!
